# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rahul Akula
tagline:          'Connect - Rahul Akula'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Rahul Akula'
  url:            https://twitter.com/rahul0611

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rahul0611
